name: ExpandableText
author: magicweb
category: Interface
tags: [expandable, text, minimised]
docs: http://www.magicwebsolutions.co.uk/demos/home.action?demo=text_description
demo: http://www.magicwebsolutions.co.uk/demos/home.action?demo=text_description